public class Control_Monad_ST_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bind_ = FFI_STUB;
    public static Object bind_(Object... args) { return null; }
    public static Object $for = FFI_STUB;
    public static Object $for(Object... args) { return null; }
    public static Object foreach = FFI_STUB;
    public static Object foreach(Object... args) { return null; }
    public static Object map_ = FFI_STUB;
    public static Object map_(Object... args) { return null; }
    public static Object modifyImpl = FFI_STUB;
    public static Object modifyImpl(Object... args) { return null; }
    public static Object $new = FFI_STUB;
    public static Object $new(Object... args) { return null; }
    public static Object pure_ = FFI_STUB;
    public static Object pure_(Object... args) { return null; }
    public static Object read = FFI_STUB;
    public static Object read(Object... args) { return null; }
    public static Object run = FFI_STUB;
    public static Object run(Object... args) { return null; }
    public static Object $while = FFI_STUB;
    public static Object $while(Object... args) { return null; }
    public static Object write = FFI_STUB;
    public static Object write(Object... args) { return null; }

public static final Object modifyprime = Control_Monad_ST_Internal.modifyImpl;
public static final Object modify = (java.util.function.Function<Object, Object>) (f_0) -> ((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.modifyImpl)).apply((java.util.function.Function<Object, Object>) (s_1) -> { Object s_prime__2 = ((java.util.function.Function<Object, Object>) (f_0)).apply(s_1); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("state", s_prime__2); __map.put("value", s_prime__2);  return __map; } }).get(); });
public static final Object functorST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", Control_Monad_ST_Internal.map_);  return __map; } }).get();
public static final Object monadST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.applicativeST); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.bindST);  return __map; } }).get();
public static final Object bindST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bind", Control_Monad_ST_Internal.bind_); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.applyST);  return __map; } }).get();
public static final Object applyST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__2 = ((java.util.function.Supplier) (Object)(f_0)).get(); Object a_prime__3 = ((java.util.function.Supplier) (Object)(a_1)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.applicativeST).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__2)).apply(a_prime__3)))).get(); } })); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.functorST);  return __map; } }).get();
public static final Object applicativeST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", Control_Monad_ST_Internal.pure_); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.applyST);  return __map; } }).get();
public static final Object semigroupST = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__3 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3 = ((java.util.function.Supplier) (Object)(a_1)).get(); return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(__local_var_3); } }).get(); Object a_prime__4 = ((java.util.function.Supplier) (Object)(b_2)).get(); return ((java.util.function.Function<Object, Object>) (f_prime__3)).apply(a_prime__4); } }));  return __map; } }).get();
public static final Object monadRecST = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("tailRecM", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_1); Object r_3 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3 = ((java.util.function.Supplier) (Object)(__local_var_2)).get(); return null /* TODO: unknown syntax PrimEffect */; } }).get(); Object _dollar___unused_4 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = null /* TODO: unknown syntax PrimEffect */; return (__local_var_4 instanceof Control_Monad_Rec_Class.Loop); } })))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object v_4 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Supplier) (Object)(( ((Boolean) ((v_4 instanceof Control_Monad_Rec_Class.Loop))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object e_5 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (f_0)).apply(((Control_Monad_Rec_Class.Loop) (Object)(v_4)).value0))).get(); Object __local_var_6 = null /* TODO: unknown syntax PrimEffect */; return Data_Unit.unit; } }) : ( ((Boolean) ((v_4 instanceof Control_Monad_Rec_Class.Done))) ? (new java.util.function.Supplier<Object>() { public Object get() { return Data_Unit.unit; } }) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))).get(); } })))).get(); Object __local_var_5 = null /* TODO: unknown syntax PrimEffect */; return ( ((Boolean) ((__local_var_5 instanceof Control_Monad_Rec_Class.Done))) ? ((Control_Monad_Rec_Class.Done) (Object)(__local_var_5)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); } })); __map.put("Monad0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_ST_Internal.monadST);  return __map; } }).get();
public static final Object monoidST = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object semigroupST1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__4 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((java.util.function.Supplier) (Object)(a_2)).get(); return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(__local_var_4); } }).get(); Object a_prime__5 = ((java.util.function.Supplier) (Object)(b_3)).get(); return ((java.util.function.Function<Object, Object>) (f_prime__4)).apply(a_prime__5); } }));  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); return __local_var_2; } })); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupST1_1);  return __map; } }).get(); };
}
