public class Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object whenM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3) -> (java.util.function.Function<Object, Object>) (m_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> ( ((Boolean) (b_5)) ? m_4 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit))); };
public static final Object unlessM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3) -> (java.util.function.Function<Object, Object>) (m_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> ( ((Boolean) (!(((Boolean) (b_5))))) ? m_4 : ( ((Boolean) (b_5)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); };
public static final Object monadProxy = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeProxy); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindProxy);  return __map; } }).get();
public static final Object monadFn = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeFn); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindFn);  return __map; } }).get();
public static final Object monadArray = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeArray); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindArray);  return __map; } }).get();
public static final Object liftM1 = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(a_prime__5))); };
public static final Object ap = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(f_3))).apply((java.util.function.Function<Object, Object>) (f_prime__5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__6) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__5)).apply(a_prime__6)))); };
}
