public class Data_Ord_Min {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Min = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showMin = (java.util.function.Function<Object, Object>) (dictShow_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Min ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object semigroupMin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_1))).apply(v1_2); return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? v_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? v_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? v1_2 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); });  return __map; } }).get();
public static final Object newtypeMin = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object monoidMin = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { Object semigroupMin1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> { Object v_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply(v_2))).apply(v1_3); return ( ((Boolean) ((v_4 instanceof Data_Ordering.LT))) ? v_2 : ( ((Boolean) ((v_4 instanceof Data_Ordering.EQ))) ? v_2 : ( ((Boolean) ((v_4 instanceof Data_Ordering.GT))) ? v1_3 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); });  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top")); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupMin1_1);  return __map; } }).get(); };
public static final Object eqMin = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object ordMin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqMin1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_2))).apply(v1_3)); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqMin1_1);  return __map; } }).get(); };
}
