public class Data_Divide {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object dividePredicate = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("divide", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> (java.util.function.Function<Object, Object>) (a_3) -> { Object v2_4 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); return (((Boolean) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_4)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_4)).value1)))); }); __map.put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Predicate.contravariantPredicate);  return __map; } }).get();
public static final Object divideOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("divide", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> (java.util.function.Function<Object, Object>) (a_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_1)).apply(a_4); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0)))).apply(((java.util.function.Function<Object, Object>) (v1_3)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1)); }); __map.put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> Data_Op.contravariantOp);  return __map; } }).get();
public static final Object divideEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("divide", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); Object v3_6 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_4); return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value1)))); }); __map.put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Equivalence.contravariantEquivalence);  return __map; } }).get();
public static final Object divideComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("divide", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); Object v3_6 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_4); Object __local_var_7 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value0); Object __local_var_8 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value1); return ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.LT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.GT))) ? new Data_Ordering.GT() : ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.EQ))) ? __local_var_8 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }); __map.put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Comparison.contravariantComparison);  return __map; } }).get();
public static final Object divide = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("divide");
public static final Object divided = (java.util.function.Function<Object, Object>) (dictDivide_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivide_0).get("divide"))).apply((java.util.function.Function<Object, Object>) (x_1) -> x_1);
}
