public class Data_Predicate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Predicate = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object newtypePredicate = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object heytingAlgebraPredicate = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("ff", (java.util.function.Function<Object, Object>) (v_0) -> false); __map.put("tt", (java.util.function.Function<Object, Object>) (v_0) -> true); __map.put("implies", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (!(((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2)))))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("conj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))) && ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("disj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("not", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)))));  return __map; } }).get();
public static final Object contravariantPredicate = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2)));  return __map; } }).get();
public static final Object booleanAlgebraPredicate = (new java.util.function.Supplier<Object>() { public Object get() { Object heytingAlgebraFunction_0 = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("ff", (java.util.function.Function<Object, Object>) (v_0) -> false); __map.put("tt", (java.util.function.Function<Object, Object>) (v_0) -> true); __map.put("implies", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (!(((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2)))))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("conj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))) && ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("disj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))))); __map.put("not", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)))));  return __map; } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> heytingAlgebraFunction_0);  return __map; } }).get(); } }).get();
}
