public class Data_Monoid_Multiplicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Multiplicative = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showMultiplicative = (java.util.function.Function<Object, Object>) (dictShow_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Multiplicative ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object semigroupMultiplicative = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("mul"))).apply(v_1))).apply(v1_2));  return __map; } }).get();
public static final Object ordMultiplicative = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object monoidMultiplicative = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { Object semigroupMultiplicative1_1 = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("mul"))).apply(v_1))).apply(v1_2));  return __map; } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", ((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("one")); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupMultiplicative1_1);  return __map; } }).get(); };
public static final Object functorMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1));  return __map; } }).get();
public static final Object eqMultiplicative = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object eq1Multiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"));  return __map; } }).get();
public static final Object ord1Multiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare")); __map.put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.eq1Multiplicative);  return __map; } }).get();
public static final Object boundedMultiplicative = (java.util.function.Function<Object, Object>) (dictBounded_0) -> dictBounded_0;
public static final Object applyMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1)); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.functorMultiplicative);  return __map; } }).get();
public static final Object bindMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bind", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0)); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.applyMultiplicative);  return __map; } }).get();
public static final Object applicativeMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", (java.util.function.Function<Object, Object>) (x_0) -> x_0); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.applyMultiplicative);  return __map; } }).get();
public static final Object monadMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.applicativeMultiplicative); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Multiplicative.bindMultiplicative);  return __map; } }).get();
}
