public class Data_Profunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object profunctorFn = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("dimap", (java.util.function.Function<Object, Object>) (a2b_0) -> (java.util.function.Function<Object, Object>) (c2d_1) -> (java.util.function.Function<Object, Object>) (b2c_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (c2d_1)).apply(((java.util.function.Function<Object, Object>) (b2c_2)).apply(((java.util.function.Function<Object, Object>) (a2b_0)).apply(x_3))));  return __map; } }).get();
public static final Object dimap = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("dimap");
public static final Object lcmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> (java.util.function.Function<Object, Object>) (a2b_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0).get("dimap"))).apply(a2b_1))).apply((java.util.function.Function<Object, Object>) (x_2) -> x_2);
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> (java.util.function.Function<Object, Object>) (b2c_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0).get("dimap"))).apply((java.util.function.Function<Object, Object>) (x_2) -> x_2))).apply(b2c_1);
public static final Object unwrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0).get("dimap"))).apply(Unsafe_Coerce.unsafeCoerce))).apply(Unsafe_Coerce.unsafeCoerce);
public static final Object wrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0).get("dimap"))).apply(Unsafe_Coerce.unsafeCoerce))).apply(Unsafe_Coerce.unsafeCoerce);
public static final Object arr = (java.util.function.Function<Object, Object>) (dictCategory_0) -> { Object identity2_1 = ((java.util.LinkedHashMap<String, Object>) dictCategory_0).get("identity"); return (java.util.function.Function<Object, Object>) (dictProfunctor_2) -> (java.util.function.Function<Object, Object>) (f_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (x_4) -> x_4))).apply(f_3))).apply(identity2_1); };
}
