public class Data_Ord_Down {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Down = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showDown = (java.util.function.Function<Object, Object>) (dictShow_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Down ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object newtypeDown = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object eqDown = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object ordDown = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqDown1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_2))).apply(v1_3); return ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqDown1_1);  return __map; } }).get(); };
public static final Object boundedDown = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { Object ordDown1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); Object eqDown1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply(v_3))).apply(v1_4); return ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eqDown1_2);  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("top", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("bottom")); __map.put("bottom", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top")); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> ordDown1_1);  return __map; } }).get(); };
}
