public class Data_Traversable_Accum_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object StateR = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object StateL = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object stateR = (java.util.function.Function<Object, Object>) (v_0) -> v_0;
public static final Object stateL = (java.util.function.Function<Object, Object>) (v_0) -> v_0;
public static final Object functorStateR = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (k_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (k_1)).apply(s_2); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", ((java.util.LinkedHashMap<String, Object>) v_3).get("accum")); __map.put("value", ((java.util.function.Function<Object, Object>) (f_0)).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("value")));  return __map; } }).get(); });  return __map; } }).get();
public static final Object functorStateL = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (k_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (k_1)).apply(s_2); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", ((java.util.LinkedHashMap<String, Object>) v_3).get("accum")); __map.put("value", ((java.util.function.Function<Object, Object>) (f_0)).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("value")));  return __map; } }).get(); });  return __map; } }).get();
public static final Object applyStateR = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (x_1)).apply(s_2); Object v1_4 = ((java.util.function.Function<Object, Object>) (f_0)).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("accum")); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", ((java.util.LinkedHashMap<String, Object>) v1_4).get("accum")); __map.put("value", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) v1_4).get("value"))).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("value")));  return __map; } }).get(); }); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Traversable_Accum_Internal.functorStateR);  return __map; } }).get();
public static final Object applyStateL = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (f_0)).apply(s_2); Object v1_4 = ((java.util.function.Function<Object, Object>) (x_1)).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("accum")); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", ((java.util.LinkedHashMap<String, Object>) v1_4).get("accum")); __map.put("value", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) v_3).get("value"))).apply(((java.util.LinkedHashMap<String, Object>) v1_4).get("value")));  return __map; } }).get(); }); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Traversable_Accum_Internal.functorStateL);  return __map; } }).get();
public static final Object applicativeStateR = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", s_1); __map.put("value", a_0);  return __map; } }).get()); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Traversable_Accum_Internal.applyStateR);  return __map; } }).get();
public static final Object applicativeStateL = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("accum", s_1); __map.put("value", a_0);  return __map; } }).get()); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Traversable_Accum_Internal.applyStateL);  return __map; } }).get();
}
