public class Data_Distributive {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object distributiveIdentity = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("distribute", (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply(Unsafe_Coerce.unsafeCoerce); return (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(x_2); }); __map.put("collect", (java.util.function.Function<Object, Object>) (dictFunctor_0) -> (java.util.function.Function<Object, Object>) (f_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(x_2)); return (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (__local_var_2)).apply(x_3); }); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Identity.functorIdentity);  return __map; } }).get();
public static final Object distribute = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("distribute");
public static final Object distributiveFunction = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("distribute", (java.util.function.Function<Object, Object>) (dictFunctor_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (e_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (v_3)).apply(e_2)))).apply(a_1)); __map.put("collect", (java.util.function.Function<Object, Object>) (dictFunctor_0) -> (java.util.function.Function<Object, Object>) (f_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Distributive.distributiveFunction).get("distribute"))).apply(dictFunctor_0); Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply(f_1); return (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (__local_var_2)).apply(((java.util.function.Function<Object, Object>) (__local_var_3)).apply(x_4)); }); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Functor.functorFn);  return __map; } }).get();
public static final Object cotraverse = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDistributive_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictFunctor_2) -> { Object distribute2_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDistributive_0).get("distribute"))).apply(dictFunctor_2); return (java.util.function.Function<Object, Object>) (f_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_4); return (java.util.function.Function<Object, Object>) (x_6) -> ((java.util.function.Function<Object, Object>) (__local_var_5)).apply(((java.util.function.Function<Object, Object>) (distribute2_3)).apply(x_6)); }; }; };
public static final Object collectDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { Object distribute2_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDistributive_0).get("distribute"))).apply(dictFunctor_1); return (java.util.function.Function<Object, Object>) (f_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_1).get("map"))).apply(f_3); return (java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (distribute2_2)).apply(((java.util.function.Function<Object, Object>) (__local_var_4)).apply(x_5)); }; };
public static final Object distributiveTuple = (java.util.function.Function<Object, Object>) (dictTypeEquals_0) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_dictTypeEquals_0 = dictTypeEquals_0; while(true) { final Object __final_dictTypeEquals_0 = __tco_dictTypeEquals_0; try { return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("collect", (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { Object distribute2_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Data_Distributive.distributiveTuple)).apply(dictTypeEquals_0)).get("distribute"))).apply(dictFunctor_1); return (java.util.function.Function<Object, Object>) (f_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_1).get("map"))).apply(f_3); return (java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (distribute2_2)).apply(((java.util.function.Function<Object, Object>) (__local_var_4)).apply(x_5)); }; }); __map.put("distribute", (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (Data_Tuple.Tuple)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictTypeEquals_0).get("proof"))).apply((java.util.function.Function<Object, Object>) (a_2) -> a_2))).apply(Data_Unit.unit)); Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_1).get("map"))).apply(Data_Tuple.snd); return (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (__local_var_2)).apply(((java.util.function.Function<Object, Object>) (__local_var_3)).apply(x_4)); }); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> Data_Tuple.functorTuple);  return __map; } }).get(); } catch (TcoLoop __tco_ex) { __tco_dictTypeEquals_0 = __tco_ex.args[0]; } } } }).get();
public static final Object collect = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("collect");
public static final Object distributeDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> (java.util.function.Function<Object, Object>) (dictFunctor_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDistributive_0).get("collect"))).apply(dictFunctor_1))).apply((java.util.function.Function<Object, Object>) (x_2) -> x_2);
}
