public class Data_Op {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Op = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object semigroupoidOp = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compose", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v1_1)).apply(((java.util.function.Function<Object, Object>) (v_0)).apply(x_2)));  return __map; } }).get();
public static final Object semigroupOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (g_2)).apply(x_3)));  return __map; } }).get();
public static final Object newtypeOp = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object monoidOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object semigroupFn_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(x_4)))).apply(((java.util.function.Function<Object, Object>) (g_3)).apply(x_4)));  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty")); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupFn_1);  return __map; } }).get(); };
public static final Object contravariantOp = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2)));  return __map; } }).get();
public static final Object categoryOp = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("identity", (java.util.function.Function<Object, Object>) (x_0) -> x_0); __map.put("Semigroupoid0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Op.semigroupoidOp);  return __map; } }).get();
}
