public class Data_Functor_Invariant {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object invariantMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2));  return __map; } }).get();
public static final Object invariantEndo = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (ab_0) -> (java.util.function.Function<Object, Object>) (ba_1) -> (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (ab_0)).apply(((java.util.function.Function<Object, Object>) (v_2)).apply(((java.util.function.Function<Object, Object>) (ba_1)).apply(x_3))));  return __map; } }).get();
public static final Object invariantDual = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2));  return __map; } }).get();
public static final Object invariantDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2));  return __map; } }).get();
public static final Object invariantConj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2));  return __map; } }).get();
public static final Object invariantAdditive = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2));  return __map; } }).get();
public static final Object imapF = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply(f_1);
public static final Object invariantArray = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (Data_Functor.arrayMap)).apply(f_0));  return __map; } }).get();
public static final Object invariantFn = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Semigroupoid.semigroupoidFn).get("compose"))).apply(f_0));  return __map; } }).get();
public static final Object imap = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("imap");
public static final Object invariantAlternate = (java.util.function.Function<Object, Object>) (dictInvariant_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("imap", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictInvariant_0).get("imap"))).apply(f_1))).apply(g_2))).apply(v_3));  return __map; } }).get();
}
