public class Data_Monoid_Disj {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Disj = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showDisj = (java.util.function.Function<Object, Object>) (dictShow_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Disj ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object semiringDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("zero", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("ff")); __map.put("one", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("tt")); __map.put("add", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2)); __map.put("mul", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("conj"))).apply(v_1))).apply(v1_2));  return __map; } }).get();
public static final Object semigroupDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2));  return __map; } }).get();
public static final Object ordDisj = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object monoidDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { Object semigroupDisj1_1 = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2));  return __map; } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("ff")); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupDisj1_1);  return __map; } }).get(); };
public static final Object functorDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1));  return __map; } }).get();
public static final Object eqDisj = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object eq1Disj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"));  return __map; } }).get();
public static final Object ord1Disj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare")); __map.put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.eq1Disj);  return __map; } }).get();
public static final Object boundedDisj = (java.util.function.Function<Object, Object>) (dictBounded_0) -> dictBounded_0;
public static final Object applyDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1)); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.functorDisj);  return __map; } }).get();
public static final Object bindDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bind", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0)); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applyDisj);  return __map; } }).get();
public static final Object applicativeDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", (java.util.function.Function<Object, Object>) (x_0) -> x_0); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applyDisj);  return __map; } }).get();
public static final Object monadDisj = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applicativeDisj); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.bindDisj);  return __map; } }).get();
}
