public class Data_Show {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object showArrayImpl = FFI_STUB;
    public static Object showArrayImpl(Object... args) { return null; }
    public static Object showCharImpl = FFI_STUB;
    public static Object showCharImpl(Object... args) { return null; }
    public static Object showIntImpl = FFI_STUB;
    public static Object showIntImpl(Object... args) { return null; }
    public static Object showNumberImpl = FFI_STUB;
    public static Object showNumberImpl(Object... args) { return null; }
    public static Object showStringImpl = FFI_STUB;
    public static Object showStringImpl(Object... args) { return null; }

public static final Object showVoid = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", Data_Void.absurd);  return __map; } }).get();
public static final Object showUnit = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> "unit");  return __map; } }).get();
public static final Object showString = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", Data_Show.showStringImpl);  return __map; } }).get();
public static final Object showRecordFieldsNil = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("showRecordFields", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> "");  return __map; } }).get();
public static final Object showRecordFields = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("showRecordFields");
public static final Object showRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (dictShowRecordFields_2) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (record_3) -> (((String) ((((String) ("{")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShowRecordFields_2).get("showRecordFields"))).apply(new Type_Proxy.Proxy()))).apply(record_3)))))) + ((String) ("}"))));  return __map; } }).get();
public static final Object showProxy = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> "Proxy");  return __map; } }).get();
public static final Object showNumber = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", Data_Show.showNumberImpl);  return __map; } }).get();
public static final Object showInt = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", Data_Show.showIntImpl);  return __map; } }).get();
public static final Object showChar = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", Data_Show.showCharImpl);  return __map; } }).get();
public static final Object showBoolean = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) (v_0)) ? "true" : "false"));  return __map; } }).get();
public static final Object show = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("show");
public static final Object showArray = (java.util.function.Function<Object, Object>) (dictShow_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", ((java.util.function.Function<Object, Object>) (Data_Show.showArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show")));  return __map; } }).get();
public static final Object showRecordFieldsCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (dictShowRecordFields_1) -> (java.util.function.Function<Object, Object>) (dictShow_2) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("showRecordFields", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (record_4) -> { Object key_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); return (((String) ((((String) ((((String) ((((String) ((((String) (" ")) + ((String) (key_5))))) + ((String) (": "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_2).get("show"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_5))).apply(record_4))))))) + ((String) (","))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShowRecordFields_1).get("showRecordFields"))).apply(new Type_Proxy.Proxy()))).apply(record_4)))); });  return __map; } }).get();
public static final Object showRecordFieldsConsNil = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("showRecordFields", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (record_3) -> { Object key_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); return (((String) ((((String) ((((String) ((((String) (" ")) + ((String) (key_4))))) + ((String) (": "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_4))).apply(record_3))))))) + ((String) (" "))); });  return __map; } }).get();
}
