public class Data_Divisible {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object divisiblePredicate = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("conquer", (java.util.function.Function<Object, Object>) (v_0) -> true); __map.put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Divide.dividePredicate);  return __map; } }).get();
public static final Object divisibleOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object divideOp_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("divide", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> (java.util.function.Function<Object, Object>) (a_5) -> { Object v2_6 = ((java.util.function.Function<Object, Object>) (f_2)).apply(a_5); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_3)).apply(((Data_Tuple.Tuple) (Object)(v2_6)).value0)))).apply(((java.util.function.Function<Object, Object>) (v1_4)).apply(((Data_Tuple.Tuple) (Object)(v2_6)).value1)); }); __map.put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> Data_Op.contravariantOp);  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("conquer", (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); return (java.util.function.Function<Object, Object>) (v_3) -> __local_var_2; } }).get()); __map.put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> divideOp_1);  return __map; } }).get(); };
public static final Object divisibleEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("conquer", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> true); __map.put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Divide.divideEquivalence);  return __map; } }).get();
public static final Object divisibleComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("conquer", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); __map.put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Divide.divideComparison);  return __map; } }).get();
public static final Object conquer = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("conquer");
}
