public class Data_Comparison {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Comparison = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object semigroupComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> { Object __local_var_2 = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (x_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (f_2)).apply(x_4); Object __local_var_6 = ((java.util.function.Function<Object, Object>) (g_3)).apply(x_4); return ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.LT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.GT))) ? new Data_Ordering.GT() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.EQ))) ? __local_var_6 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); });  return __map; } }).get(); return (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_0)).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (v1_1)).apply(x_3)); });  return __map; } }).get();
public static final Object newtypeComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object monoidComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Comparison.semigroupComparison);  return __map; } }).get();
public static final Object defaultComparison = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare");
public static final Object contravariantComparison = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(y_3)));  return __map; } }).get();
}
