public class Effect {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bindE = FFI_STUB;
    public static Object bindE(Object... args) { return null; }
    public static Object forE = FFI_STUB;
    public static Object forE(Object... args) { return null; }
    public static Object foreachE = FFI_STUB;
    public static Object foreachE(Object... args) { return null; }
    public static Object pureE = FFI_STUB;
    public static Object pureE(Object... args) { return null; }
    public static Object untilE = FFI_STUB;
    public static Object untilE(Object... args) { return null; }
    public static Object whileE = FFI_STUB;
    public static Object whileE(Object... args) { return null; }

public static final Object monadEffect = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applicativeEffect); __map.put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.bindEffect);  return __map; } }).get();
public static final Object bindEffect = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bind", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Supplier<Object>) () -> { return ((java.util.function.Supplier<Object>) ((java.util.function.Function<Object, Object>) f).apply(((java.util.function.Supplier<Object>) a).get())).get(); }); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applyEffect);  return __map; } }).get();
public static final Object applyEffect = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__2 = ((java.util.function.Supplier) (Object)(f_0)).get(); Object a_prime__3 = ((java.util.function.Supplier) (Object)(a_1)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applicativeEffect).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__2)).apply(a_prime__3)))).get(); } })); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.functorEffect);  return __map; } }).get();
public static final Object applicativeEffect = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("pure", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Supplier<Object>) () -> a); __map.put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applyEffect);  return __map; } }).get();
public static final Object functorEffect = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object a_prime__2 = ((java.util.function.Supplier) (Object)(a_1)).get(); return ((java.util.function.Function<Object, Object>) (f_0)).apply(a_prime__2); } }));  return __map; } }).get();
public static final Object semigroupEffect = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__3 = (new java.util.function.Supplier<Object>() { public Object get() { Object a_prime__3 = ((java.util.function.Supplier) (Object)(a_1)).get(); return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(a_prime__3); } }).get(); Object a_prime__4 = ((java.util.function.Supplier) (Object)(b_2)).get(); return ((java.util.function.Function<Object, Object>) (f_prime__3)).apply(a_prime__4); } }));  return __map; } }).get();
public static final Object monoidEffect = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object semigroupEffect1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object f_prime__4 = (new java.util.function.Supplier<Object>() { public Object get() { Object a_prime__4 = ((java.util.function.Supplier) (Object)(a_2)).get(); return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(a_prime__4); } }).get(); Object a_prime__5 = ((java.util.function.Supplier) (Object)(b_3)).get(); return ((java.util.function.Function<Object, Object>) (f_prime__4)).apply(a_prime__5); } }));  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); return __local_var_2; } })); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupEffect1_1);  return __map; } }).get(); };
}
